package com.messi.languagehelper.meinv.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.messi.languagehelper.meinv.dao.Avobject;

import com.messi.languagehelper.meinv.dao.AvobjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig avobjectDaoConfig;

    private final AvobjectDao avobjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        avobjectDaoConfig = daoConfigMap.get(AvobjectDao.class).clone();
        avobjectDaoConfig.initIdentityScope(type);

        avobjectDao = new AvobjectDao(avobjectDaoConfig, this);

        registerDao(Avobject.class, avobjectDao);
    }
    
    public void clear() {
        avobjectDaoConfig.clearIdentityScope();
    }

    public AvobjectDao getAvobjectDao() {
        return avobjectDao;
    }

}
